name: GitHub Actions Demo - Shubham Agrawal

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Output event name
        run: | 
          echo "Event name: ${{github.event_name}}"

      - name: Output branch name
        run: | 
          echo "Branch name: ${{github.ref}}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: List all files
        run: ls -la
